# argo-apps/foundation-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-foundation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/minnelab/manifests.git'
    targetRevision: HEAD
    path: 'layers/01-foundation'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Critical for Istio CRDs
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m